name: Simple Deployment

on:
  push:
    branches: [production]
# hi
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/services/nuxt_microservice
            # Remove any GitHub-injected extra headers that can break pulls on the VPS
            git config --global --unset-all http.https://github.com/.extraheader || true
            git config --system --unset-all http.https://github.com/.extraheader || true
            git config --local --unset-all http.https://github.com/.extraheader || true
            # Mark repo as safe directory to avoid ownership warnings
            git config --global --add safe.directory /root/services/nuxt_microservice || true
            set -e
            git fetch --all --prune
            git checkout production || git checkout -b production
            # Discard any local changes to ensure clean deployment
            git reset --hard origin/production
            git clean -fd

            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d

            docker image prune -f
